#!/bin/sh
### BEGIN INIT INFO
# Provides:          create-exfat-partition
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Creates the user exFAT partition
# Description:
### END INIT INFO

set +e

case "$1" in
  start)
    echo "Resizing exFAT partition..."
    DEVICE="/dev/mmcblk0"
    NEW_PARTITION_NUM="3"
    NEW_PARTITION="${DEVICE}p${NEW_PARTITION_NUM}"
    MOUNT_POINT="/media/sd"
    P2="/sys/block/mmcblk0/mmcblk0p2"
    START=$(( $(cat "$P2/start") + $(cat "$P2/size") ))

    # Ensure mount folder
    mkdir -p "$MOUNT_POINT"

    echo "Creating new partition with fdisk..."
    (
        printf 'n\n'                       # new
        printf 'p\n'                       # primary
        printf '%s\n' "$NEW_PARTITION_NUM"
        printf '%s\n' "$START"
        printf '\n'                        # to the end
        printf 't\n'                       # change type
        printf '%s\n' "$NEW_PARTITION_NUM"
        printf '7\n'                       # 0x07
        printf 'w\n'                       # write
    ) | fdisk "$DEVICE"

    # Create exFAT filesystem
    mkfs.exfat -n "replay" "$NEW_PARTITION"

    # fstab: add exfat mount point
    sed -i '\|/dev/mmcblk0p3|d' /etc/fstab
    echo "/dev/mmcblk0p3  ${MOUNT_POINT}  exfat  rw,noatime,nodiratime,uid=0,gid=0,fmask=0022,dmask=0022  0  0" >> /etc/fstab

    # One-time run cleanup and enable frontend
    update-rc.d create-exfat-partition.sh remove
    rm -f /etc/init.d/create-exfat-partition.sh
    systemctl enable replay.service

    echo "Rebooting to apply changes..."
    reboot
    ;;
  stop) ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
